### PR TITLE
fix: typos, small optimisations

### PR DESCRIPTION
**Pull request by mb6ockatf**

### CODE REVIEW

**Comment by mb6ockatf** [comment]
something is wrong with my email. @IvanIsak2000 see this account who did the commit? it is my account that i deleted kind of 3 years ago. so weird

i thing it will be fixed as i change my email

**Comment by IvanIsak2000** [comment]
I see this 

image

**Comment by mb6ockatf** [comment]
> I see this
> 
> image

@IvanIsak2000 see profile photo of a guy who did the commit? [this one](https://github.com/mdddmmmm)

**Comment by IvanIsak2000** [comment]
> 

yes 

image

**Comment by mb6ockatf** [comment]
> > 
> 
> yes
> 
> image

this is my old account )) i deleted it after i moved to bitbucket, then i moved back to github and now here we go

**Comment by mb6ockatf** [comment]
@IvanIsak2000 could you please press the merge button?)

**Comment by mb6ockatf** [comment]
@IvanIsak2000 thanks much)

**Pull request merged**
